import { makeStyles } from '@material-ui/core/styles';

export const useAuthStyles = makeStyles((theme) => ({
  title: {
    fontFamily: 'Comfortaa',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '32px',
    color: '#333333',
  },
  note: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '18px',
    lineHeight: '27px',
    color: '#828282',
    '& a': {
      color: '#FF8070',
      textDecoration: 'underline',
      '&:hover': {
        textDecoration: 'none',
      },
    },
  },
  forgotPassword: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '14px',
    lineHeight: '22px',
    maxWidth: '330px',
    display: 'block',
    color: '#828282',
    '& a': {
      color: '#FF8070',
      textDecoration: 'underline',
      cursor: 'pointer',
      '&:hover': {
        textDecoration: 'none',
      },
    },
  },
  termsOfUse: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '14px',
    lineHeight: '22px',
    maxWidth: '330px',
    display: 'block',
    color: '#828282',
    '& a': {
      color: '#FF8070',
      textDecoration: 'underline',
      cursor: 'pointer',
      '&:hover': {
        textDecoration: 'none',
      },
    },
  },
  createWith: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '14px',
    lineHeight: '22px',
    maxWidth: '330px',
    display: 'block',
    color: '#828282',
    marginTop: '30px',
    marginBottom: '30px',
  },
  inputsContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    marginTop: '30px',
  },
  buttonsContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    marginTop: '30px',
  },

  termsOfUse__modal: {
    position: 'relative',
  },
  termsOfUse__modalOverlay: {
    position: 'fixed',
    width: '100%',
    height: '100%',
    top: '0',
    left: '0',
    backgroundColor: 'rgba(0,0,0,0.5)',
    zIndex: 3,
    cursor: 'pointer',
  },
  termsOfUse__modalContainer: {
    position: 'fixed',
    width: '785px',
    height: '80%',
    top: '10%',
    left: '50%',
    transform: 'translateX(-50%)',
    backgroundColor: '#FAFAFA',
    zIndex: 4,
    display: 'flex',
    flexDirection: 'column',
  },
  termsOfUse__modalHeader: {
    backgroundColor: 'white',
    padding: '20px 32px',
    display: 'flex',
    justifyContent: 'space-between',
    alignContent: 'center',

    '& h3': {
      fontFamily: 'Poppins',
      fontStyle: 'normal',
      fontWeight: '400',
      fontSize: '22px',
      color: '#333333',
      margin: '0',
      padding: '0',
    },
  },
  termsOfUse__modalClose: {
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    '& svg': {
      fill: '#BDBDBD',
    },
  },
  termsOfUse__modalFooter: {
    backgroundColor: 'white',
    padding: '20px 32px',
    display: 'flex',
    justifyContent: 'flex-end',
  },
  termsOfUse__buttonsContainer: {
    textAlign: 'right',
  },
  termsText: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 16,
    lineHeight: '150%',
    letterSpacing: '0.001em',
  },
}));
