export const supplierColumns = [
  { id: 'name', info: 'name', label: 'Name', editable: false },
  {
    id: 'customer',
    label: 'Customer',
    editable: false,
  },
  {
    id: 'amount',
    label: 'Amount',
    editable: false,
  },
  {
    id: 'products',
    label: 'Products',
    editable: false,
  },
  {
    id: 'status',
    label: 'Status',
    editable: false,
  },
  {
    id: 'sendDate',
    label: 'Send Date',
    editable: true,
  },
];

export const supplierData = [
  {
    _id: 1,
    name: 'name',
    customer: 'customer',
    amount: '$601',
    products: '27',
    status: 'Sent',
    sendDate: 'June 11, 2020',
  },
  {
    _id: 2,
    name: 'name',
    customer: 'customer',
    amount: '$601',
    products: '27',
    status: 'Sent',
    sendDate: 'June 11, 2020',
  },
  {
    _id: 3,
    name: 'name',
    customer: 'customer',
    amount: '$601',
    products: '27',
    status: 'Sent',
    sendDate: 'June 11, 2020',
  },
  {
    _id: 4,
    name: 'name',
    customer: 'customer',
    amount: '$601',
    products: '27',
    status: 'Sent',
    sendDate: 'June 11, 2020',
  },
  {
    _id: 5,
    name: 'name',
    customer: 'customer',
    amount: '$601',
    products: '27',
    status: 'Sent',
    sendDate: 'June 11, 2020',
  },
  {
    _id: 6,
    name: 'name',
    customer: 'customer',
    amount: '$601',
    products: '27',
    status: 'Sent',
    sendDate: 'June 11, 2020',
  },
  {
    _id: 7,
    name: 'name',
    customer: 'customer',
    amount: '$601',
    products: '27',
    status: 'Sent',
    sendDate: 'June 11, 2020',
  },
];
