export const SupplierData = [
  {
    _id: '1',
    name: 'pn1',
    sku: '342873427',
    category: 'category 1',
    manufacturer: 'man1',
    totalRfq: 3,
    openRfq: '1',
    catalogPrice: '1',
    bestPrice: '1',
    lastQuote: '1',
  },
  {
    _id: '2',
    name: 'pn2',
    sku: '342873427',
    category: 'category 2',
    manufacturer: 'man2',
    totalRfq: 3,
    openRfq: '2',
    catalogPrice: '2',
    bestPrice: '2',
    lastQuote: '2',
  },
  {
    _id: '3',
    name: 'pn3',
    sku: '342873427',
    category: 'category 3',
    manufacturer: 'man3',
    totalRfq: 3,
    openRfq: '3',
    catalogPrice: '3',
    bestPrice: '3',
    lastQuote: '3',
  },
  {
    _id: '4',
    name: 'pn4',
    sku: '342873427',
    category: 'category 4',
    manufacturer: 'man4',
    totalRfq: 3,
    openRfq: '4',
    catalogPrice: '4',
    bestPrice: '4',
    lastQuote: '4',
  },
  {
    _id: '5',
    name: 'pn5',
    sku: '342873427',
    category: 'category 5',
    manufacturer: 'man5',
    totalRfq: 3,
    openRfq: '5',
    catalogPrice: '5',
    bestPrice: '5',
    lastQuote: '5',
  },
  {
    _id: '6',
    name: 'pn6',
    sku: '342873427',
    category: 'category 6',
    manufacturer: 'man6',
    totalRfq: 3,
    openRfq: '6',
    catalogPrice: '6',
    bestPrice: '6',
    lastQuote: '6',
  },
  {
    _id: '7',
    name: 'pn7',
    sku: '342873427',
    category: 'category 7',
    manufacturer: 'man7',
    totalRfq: 3,
    openRfq: '7',
    catalogPrice: '7',
    bestPrice: '7',
    lastQuote: '7',
  },
  {
    _id: '8',
    name: 'pn8',
    sku: '342873427',
    category: 'category 8',
    manufacturer: 'man8',
    totalRfq: 3,
    openRfq: '8',
    catalogPrice: '8',
    bestPrice: '8',
    lastQuote: '8',
  },
  {
    _id: '9',
    name: 'pn9',
    sku: '342873427',
    category: 'category 9',
    manufacturer: 'man9',
    totalRfq: 3,
    openRfq: '9',
    catalogPrice: '9',
    bestPrice: '9',
    lastQuote: '9',
  },
];

export const SupplierColumns = [
  {
    id: 'name',
    info: 'name',
    label: 'Product Name',
    editable: true,
    isDefaultModeAvailable: true,
  },
  { id: 'sku', label: 'SKU', editable: true, isDefaultModeAvailable: true },
  {
    id: 'category',
    label: 'Category',
    editable: false,
    expandedLabel: 'Category Tree',
    isDefaultModeAvailable: true,
  },
  {
    id: 'manufacturer',
    label: 'Manufacturer',
    editable: true,
    isDefaultModeAvailable: true,
    isDropDown: true,
  },
  {
    id: 'totalRfq',
    label: 'Total RFQ',
    editable: false,
    isDefaultModeAvailable: false,
  },
  {
    id: 'openRfq',
    label: 'Open RFQ',
    editable: false,
    isDefaultModeAvailable: true,
  },
  {
    id: 'catalogPrice',
    label: 'Catalog Price',
    editable: true,
    isDefaultModeAvailable: true,
  },
  {
    id: 'bestPrice',
    label: 'Best Price',
    editable: false,
    isDefaultModeAvailable: true,
  },
  {
    id: 'lastQuote',
    label: 'Last Quote',
    editable: false,
    isDefaultModeAvailable: true,
  },
];
