export const quotesCustomerColumns = [
  { id: 'name', info: 'name', label: 'Name', editable: false },
  {
    id: 'products',
    label: 'Products',
    editable: false,
    expandedLabel: 'Products',
  },
  {
    id: 'amount',
    label: 'Amount',
    editable: false,
  },
  {
    id: 'status',
    label: 'Status',
    editable: false,
  },
  {
    id: 'suppliers',
    label: 'Suppliers',
    editable: false,
  },
  {
    id: 'responses',
    label: 'Responses',
    editable: false,
  },
  {
    id: 'sendDate',
    label: 'Send Date',
    editable: false,
  },
];

export const customerData = [
  {
    _id: 1,
    name: 'name',
    products: '38',
    amount: '$601',
    status: 'Draft',
    sendDate: 'June 11, 2020',
    responses: '80',
    suppliers: '78',
  },
  {
    _id: 2,
    name: 'name',
    products: '38',
    amount: '$601',
    status: 'Draft',
    sendDate: 'June 11, 2020',
    responses: '80',
    suppliers: '78',
  },
  {
    _id: 3,
    name: 'name',
    products: '38',
    amount: '$601',
    status: 'Draft',
    sendDate: 'June 11, 2020',
    responses: '80',
    suppliers: '78',
  },
  {
    _id: 4,
    name: 'name',
    products: '38',
    amount: '$601',
    status: 'Draft',
    sendDate: 'June 11, 2020',
    responses: '80',
    suppliers: '78',
  },
  {
    _id: 5,
    name: 'name',
    products: '38',
    amount: '$601',
    status: 'Draft',
    sendDate: 'June 11, 2020',
    responses: '80',
    suppliers: '78',
  },
  {
    _id: 6,
    name: 'name',
    products: '38',
    amount: '$601',
    status: 'Draft',
    sendDate: 'June 11, 2020',
    responses: '80',
    suppliers: '78',
  },
];
